---

- name: Assert required variables
  assert:
    that:
      - openvpn_server__packages_source in ['os', 'openvpn']
      - openvpn_server__provider_version in ['stable', 'testing', 'release/2.3', 'release/2.4']
