---

- name: Install required packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ openvpn_server__required_packages_names }}'

- name: Fail if architecture is not supported
  fail:
    msg: '{{ ansible_architecture }} architecture is not supported'
  when: openvpn_server__packages_source == 'openvpn'
    and ansible_architecture not in ['x86_64']

- name: Include installation tasks from openvpn repository
  include_tasks: '{{ file_item }}'
  with_first_found:
    - files:
        - 'install-openvpn-{{ ansible_distribution }}.yml'
        - 'install-openvpn-{{ ansible_os_family }}.yml'
  when: openvpn_server__packages_source == 'openvpn'
  loop_control:
    loop_var: file_item

- name: Install openvpn packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ openvpn__packages_names }}'
