---

- name: Install systemd overriding unit directory
  file:
    path: "/etc/systemd/system/{{ openvpn__service_name|replace('%i', '') }}.service.d/"
    state: directory

- name: Install systemd overriding unit file
  template:
    src: openvpn.override.service.j2
    dest: "/etc/systemd/system/{{ openvpn__service_name|replace('%i', '') }}.service.d/override.conf"
    owner: root
    group: root
    mode: 0755
  register: _openvpn__service
  notify: ['restart-openvpn']

- name: Remove sysvinit unit file
  file:
    path: '{{ openvpn__service_sysvinit_file }}'
    state: absent
  register: _openvpn__service_sysvinit
  when: openvpn__service_sysvinit_file is defined

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: _openvpn__service is changed or _openvpn__service_sysvinit is changed
  changed_when: true

- meta: flush_handlers
